# Generated by Django 4.2.1 on 2023-06-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0002_alter_category_categoryname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bought',
            name='PurchasedPrice',
        ),
    ]
