# Generated by Django 4.2.1 on 2023-06-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0003_remove_bought_purchasedprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='PhoneNumber',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
