# Generated by Django 4.2.1 on 2023-06-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0004_bill_email_bill_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='Email',
            new_name='Adress',
        ),
    ]
