# Generated by Django 4.2.1 on 2023-06-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0005_rename_email_bill_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='Adress',
            new_name='Address',
        ),
    ]
