# Generated by Django 4.2.1 on 2023-06-09 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0006_rename_adress_bill_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Status', models.CharField(max_length=255)),
                ('Amount', models.IntegerField(null=True)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('PhoneNumber', models.CharField(max_length=255, null=True)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.book')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='bought',
            name='Bill',
        ),
        migrations.RemoveField(
            model_name='bought',
            name='Book',
        ),
        migrations.RemoveField(
            model_name='bought',
            name='User',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Bought',
        ),
    ]
